// AUTO-GENERATED by dev-tools/generate-crud.mjs - do not edit by hand.
// Imported by server.js to mount every generated CRUD module in one place.
export async function loadGeneratedRoutes() {
  return [
  { path: '/api/roles', route: (await import('./rolesRoutes.js')).default },
  { path: '/api/categories', route: (await import('./categoriesRoutes.js')).default },
  { path: '/api/brands', route: (await import('./brandsRoutes.js')).default },
  { path: '/api/units', route: (await import('./unitsRoutes.js')).default },
  { path: '/api/warehouses', route: (await import('./warehousesRoutes.js')).default },
  { path: '/api/products', route: (await import('./productsRoutes.js')).default },
  { path: '/api/accounts', route: (await import('./accountsRoutes.js')).default },
  { path: '/api/bank-accounts', route: (await import('./bank-accountsRoutes.js')).default },
  { path: '/api/payment-methods', route: (await import('./payment-methodsRoutes.js')).default },
  { path: '/api/opening-stocks', route: (await import('./opening-stocksRoutes.js')).default },
  { path: '/api/opening-balances', route: (await import('./opening-balancesRoutes.js')).default },
  { path: '/api/suppliers', route: (await import('./suppliersRoutes.js')).default },
  { path: '/api/customers', route: (await import('./customersRoutes.js')).default },
  { path: '/api/employees', route: (await import('./employeesRoutes.js')).default },
  { path: '/api/purchase-orders', route: (await import('./purchase-ordersRoutes.js')).default },
  { path: '/api/purchases', route: (await import('./purchasesRoutes.js')).default },
  { path: '/api/purchase-returns', route: (await import('./purchase-returnsRoutes.js')).default },
  { path: '/api/payments', route: (await import('./paymentsRoutes.js')).default },
  { path: '/api/receipts', route: (await import('./receiptsRoutes.js')).default },
  { path: '/api/journal-entries', route: (await import('./journal-entriesRoutes.js')).default },
  { path: '/api/expenses', route: (await import('./expensesRoutes.js')).default },
  { path: '/api/quotations', route: (await import('./quotationsRoutes.js')).default },
  { path: '/api/sales-orders', route: (await import('./sales-ordersRoutes.js')).default },
  { path: '/api/sales-returns', route: (await import('./sales-returnsRoutes.js')).default },
  { path: '/api/sales', route: (await import('./salesRoutes.js')).default },
  { path: '/api/damages', route: (await import('./damagesRoutes.js')).default },
  { path: '/api/stock-transfers', route: (await import('./stock-transfersRoutes.js')).default },
  { path: '/api/stock-adjustments', route: (await import('./stock-adjustmentsRoutes.js')).default },
  ];
}
