// ============================================================================
// Master entity configuration used to generate backend Mongoose models,
// controllers and routes. This file is the single source of truth for every
// data-driven module in the Business Panel app. To add a brand new module:
//   1. Add a new entry to the `entities` array below.
//   2. Run:  node dev-tools/generate-crud.mjs
//   3. Mount the new route in backend/server.js
//   4. Add a matching entry to frontend/src/config/entities.js
// ============================================================================

export const entities = [
  {
    key: 'roles',
    model: 'Role',
    label: 'Role',
    labelPlural: 'Roles',
    fields: [
      { name: 'name', type: 'String', required: true, unique: true },
      { name: 'description', type: 'String' },
      { name: 'permissions', type: 'Array', of: 'String', default: [] },
    ],
  },
  {
    key: 'categories',
    model: 'Category',
    label: 'Category',
    labelPlural: 'Categories',
    fields: [
      { name: 'name', type: 'String', required: true, unique: true },
      { name: 'description', type: 'String' },
    ],
  },
  {
    key: 'brands',
    model: 'Brand',
    label: 'Brand',
    labelPlural: 'Brands',
    fields: [
      { name: 'name', type: 'String', required: true, unique: true },
      { name: 'description', type: 'String' },
    ],
  },
  {
    key: 'units',
    model: 'Unit',
    label: 'Unit',
    labelPlural: 'Units',
    fields: [
      { name: 'name', type: 'String', required: true, unique: true },
      { name: 'shortName', type: 'String' },
    ],
  },
  {
    key: 'warehouses',
    model: 'Warehouse',
    label: 'Warehouse',
    labelPlural: 'Warehouses',
    fields: [
      { name: 'name', type: 'String', required: true, unique: true },
      { name: 'location', type: 'String' },
      { name: 'phone', type: 'String' },
    ],
  },
  {
    key: 'products',
    model: 'Product',
    label: 'Product',
    labelPlural: 'Products',
    fields: [
      { name: 'name', type: 'String', required: true },
      { name: 'sku', type: 'String', required: true, unique: true },
      { name: 'category', type: 'ObjectId', ref: 'Category' },
      { name: 'brand', type: 'ObjectId', ref: 'Brand' },
      { name: 'unit', type: 'ObjectId', ref: 'Unit' },
      { name: 'warehouse', type: 'ObjectId', ref: 'Warehouse' },
      { name: 'purchasePrice', type: 'Number', default: 0 },
      { name: 'salePrice', type: 'Number', default: 0 },
      { name: 'stockQty', type: 'Number', default: 0 },
      { name: 'reorderLevel', type: 'Number', default: 0 },
      { name: 'image', type: 'String' },
      {
        name: 'status',
        type: 'String',
        enum: ['active', 'inactive'],
        default: 'active',
      },
    ],
  },
  {
    key: 'accounts',
    model: 'Account',
    label: 'Account',
    labelPlural: 'Accounts',
    fields: [
      { name: 'name', type: 'String', required: true },
      {
        name: 'accountType',
        type: 'String',
        enum: ['Asset', 'Liability', 'Equity', 'Income', 'Expense'],
        default: 'Asset',
      },
      { name: 'openingBalance', type: 'Number', default: 0 },
      { name: 'currentBalance', type: 'Number', default: 0 },
      { name: 'description', type: 'String' },
    ],
  },
  {
    key: 'bank-accounts',
    model: 'BankAccount',
    label: 'Bank Account',
    labelPlural: 'Bank Accounts',
    fields: [
      { name: 'bankName', type: 'String', required: true },
      { name: 'accountName', type: 'String', required: true },
      { name: 'accountNumber', type: 'String', required: true, unique: true },
      { name: 'branch', type: 'String' },
      { name: 'openingBalance', type: 'Number', default: 0 },
      { name: 'currentBalance', type: 'Number', default: 0 },
    ],
  },
  {
    key: 'payment-methods',
    model: 'PaymentMethod',
    label: 'Payment Method',
    labelPlural: 'Payment Methods',
    fields: [
      { name: 'name', type: 'String', required: true, unique: true },
      {
        name: 'type',
        type: 'String',
        enum: ['Cash', 'Bank', 'Mobile Banking', 'Card', 'Other'],
        default: 'Cash',
      },
      { name: 'description', type: 'String' },
    ],
  },
  {
    key: 'opening-stocks',
    model: 'OpeningStock',
    label: 'Opening Stock',
    labelPlural: 'Opening Stocks',
    fields: [
      { name: 'product', type: 'ObjectId', ref: 'Product', required: true },
      { name: 'warehouse', type: 'ObjectId', ref: 'Warehouse' },
      { name: 'quantity', type: 'Number', required: true, default: 0 },
      { name: 'unitCost', type: 'Number', default: 0 },
      { name: 'date', type: 'Date', default: 'Date.now' },
    ],
  },
  {
    key: 'opening-balances',
    model: 'OpeningBalance',
    label: 'Opening Balance',
    labelPlural: 'Opening Balances',
    fields: [
      { name: 'account', type: 'ObjectId', ref: 'Account', required: true },
      { name: 'amount', type: 'Number', required: true, default: 0 },
      {
        name: 'type',
        type: 'String',
        enum: ['Debit', 'Credit'],
        default: 'Debit',
      },
      { name: 'date', type: 'Date', default: 'Date.now' },
      { name: 'note', type: 'String' },
    ],
  },
  {
    key: 'suppliers',
    model: 'Supplier',
    label: 'Supplier',
    labelPlural: 'Suppliers',
    fields: [
      { name: 'name', type: 'String', required: true },
      { name: 'company', type: 'String' },
      { name: 'phone', type: 'String' },
      { name: 'email', type: 'String' },
      { name: 'address', type: 'String' },
      { name: 'openingBalance', type: 'Number', default: 0 },
      {
        name: 'status',
        type: 'String',
        enum: ['active', 'inactive'],
        default: 'active',
      },
    ],
  },
  {
    key: 'customers',
    model: 'Customer',
    label: 'Customer',
    labelPlural: 'Customers',
    fields: [
      { name: 'name', type: 'String', required: true },
      { name: 'phone', type: 'String' },
      { name: 'email', type: 'String' },
      { name: 'address', type: 'String' },
      { name: 'openingBalance', type: 'Number', default: 0 },
      {
        name: 'status',
        type: 'String',
        enum: ['active', 'inactive'],
        default: 'active',
      },
    ],
  },
  {
    key: 'employees',
    model: 'Employee',
    label: 'Employee',
    labelPlural: 'Employees',
    fields: [
      { name: 'name', type: 'String', required: true },
      { name: 'designation', type: 'String' },
      { name: 'phone', type: 'String' },
      { name: 'email', type: 'String' },
      { name: 'address', type: 'String' },
      { name: 'salary', type: 'Number', default: 0 },
      { name: 'joiningDate', type: 'Date' },
      {
        name: 'status',
        type: 'String',
        enum: ['active', 'inactive'],
        default: 'active',
      },
    ],
  },
  {
    key: 'purchase-orders',
    model: 'PurchaseOrder',
    label: 'Purchase Order',
    labelPlural: 'Purchase Orders',
    fields: [
      { name: 'poNumber', type: 'String', required: true, unique: true },
      { name: 'supplier', type: 'ObjectId', ref: 'Supplier', required: true },
      { name: 'orderDate', type: 'Date', default: 'Date.now' },
      { name: 'expectedDate', type: 'Date' },
      {
        name: 'status',
        type: 'String',
        enum: ['Pending', 'Approved', 'Received', 'Cancelled'],
        default: 'Pending',
      },
      { name: 'items', type: 'ItemsArray' },
      { name: 'totalAmount', type: 'Number', default: 0 },
      { name: 'note', type: 'String' },
    ],
  },
  {
    key: 'purchases',
    model: 'Purchase',
    label: 'Purchase',
    labelPlural: 'Purchases',
    fields: [
      { name: 'invoiceNumber', type: 'String', required: true, unique: true },
      { name: 'supplier', type: 'ObjectId', ref: 'Supplier', required: true },
      { name: 'warehouse', type: 'ObjectId', ref: 'Warehouse' },
      { name: 'purchaseDate', type: 'Date', default: 'Date.now' },
      { name: 'items', type: 'ItemsArray' },
      { name: 'totalAmount', type: 'Number', default: 0 },
      { name: 'paidAmount', type: 'Number', default: 0 },
      { name: 'dueAmount', type: 'Number', default: 0 },
      {
        name: 'status',
        type: 'String',
        enum: ['Pending', 'Completed'],
        default: 'Completed',
      },
      { name: 'note', type: 'String' },
    ],
  },
  {
    key: 'purchase-returns',
    model: 'PurchaseReturn',
    label: 'Purchase Return',
    labelPlural: 'Purchase Returns',
    fields: [
      { name: 'returnNumber', type: 'String', required: true, unique: true },
      { name: 'supplier', type: 'ObjectId', ref: 'Supplier' },
      { name: 'purchase', type: 'ObjectId', ref: 'Purchase' },
      { name: 'returnDate', type: 'Date', default: 'Date.now' },
      { name: 'items', type: 'ItemsArray' },
      { name: 'totalAmount', type: 'Number', default: 0 },
      { name: 'reason', type: 'String' },
    ],
  },
  {
    key: 'payments',
    model: 'Payment',
    label: 'Payment',
    labelPlural: 'Payments',
    fields: [
      { name: 'paymentNumber', type: 'String', required: true, unique: true },
      { name: 'supplier', type: 'ObjectId', ref: 'Supplier' },
      { name: 'paymentMethod', type: 'ObjectId', ref: 'PaymentMethod' },
      { name: 'amount', type: 'Number', required: true, default: 0 },
      { name: 'date', type: 'Date', default: 'Date.now' },
      { name: 'note', type: 'String' },
    ],
  },
  {
    key: 'receipts',
    model: 'Receipt',
    label: 'Receipt',
    labelPlural: 'Receipts',
    fields: [
      { name: 'receiptNumber', type: 'String', required: true, unique: true },
      { name: 'customer', type: 'ObjectId', ref: 'Customer' },
      { name: 'paymentMethod', type: 'ObjectId', ref: 'PaymentMethod' },
      { name: 'amount', type: 'Number', required: true, default: 0 },
      { name: 'date', type: 'Date', default: 'Date.now' },
      { name: 'note', type: 'String' },
    ],
  },
  {
    key: 'journal-entries',
    model: 'JournalEntry',
    label: 'Journal Entry',
    labelPlural: 'Journal Entries',
    fields: [
      { name: 'entryNumber', type: 'String', required: true, unique: true },
      { name: 'date', type: 'Date', default: 'Date.now' },
      { name: 'debitAccount', type: 'ObjectId', ref: 'Account' },
      { name: 'creditAccount', type: 'ObjectId', ref: 'Account' },
      { name: 'amount', type: 'Number', required: true, default: 0 },
      { name: 'description', type: 'String' },
    ],
  },
  {
    key: 'expenses',
    model: 'Expense',
    label: 'Expense',
    labelPlural: 'Expenses',
    fields: [
      { name: 'title', type: 'String', required: true },
      { name: 'category', type: 'String' },
      { name: 'amount', type: 'Number', required: true, default: 0 },
      { name: 'date', type: 'Date', default: 'Date.now' },
      { name: 'paymentMethod', type: 'ObjectId', ref: 'PaymentMethod' },
      { name: 'note', type: 'String' },
    ],
  },
  {
    key: 'quotations',
    model: 'Quotation',
    label: 'Quotation',
    labelPlural: 'Quotations',
    fields: [
      { name: 'quoteNumber', type: 'String', required: true, unique: true },
      { name: 'customer', type: 'ObjectId', ref: 'Customer', required: true },
      { name: 'date', type: 'Date', default: 'Date.now' },
      { name: 'validUntil', type: 'Date' },
      { name: 'items', type: 'ItemsArray', priceField: 'unitPrice' },
      { name: 'totalAmount', type: 'Number', default: 0 },
      {
        name: 'status',
        type: 'String',
        enum: ['Draft', 'Sent', 'Accepted', 'Rejected'],
        default: 'Draft',
      },
    ],
  },
  {
    key: 'sales-orders',
    model: 'SalesOrder',
    label: 'Sales Order',
    labelPlural: 'Sales Orders',
    fields: [
      { name: 'orderNumber', type: 'String', required: true, unique: true },
      { name: 'customer', type: 'ObjectId', ref: 'Customer', required: true },
      { name: 'orderDate', type: 'Date', default: 'Date.now' },
      { name: 'items', type: 'ItemsArray', priceField: 'unitPrice' },
      { name: 'totalAmount', type: 'Number', default: 0 },
      {
        name: 'status',
        type: 'String',
        enum: ['Pending', 'Confirmed', 'Delivered', 'Cancelled'],
        default: 'Pending',
      },
    ],
  },
  {
    key: 'sales-returns',
    model: 'SalesReturn',
    label: 'Sales Return',
    labelPlural: 'Sales Returns',
    fields: [
      { name: 'returnNumber', type: 'String', required: true, unique: true },
      { name: 'customer', type: 'ObjectId', ref: 'Customer' },
      { name: 'sale', type: 'ObjectId', ref: 'Sale' },
      { name: 'returnDate', type: 'Date', default: 'Date.now' },
      { name: 'items', type: 'ItemsArray', priceField: 'unitPrice' },
      { name: 'totalAmount', type: 'Number', default: 0 },
      { name: 'reason', type: 'String' },
    ],
  },
  {
    key: 'sales',
    model: 'Sale',
    label: 'Sale',
    labelPlural: 'Sales',
    fields: [
      { name: 'invoiceNumber', type: 'String', required: true, unique: true },
      { name: 'customer', type: 'ObjectId', ref: 'Customer' },
      { name: 'warehouse', type: 'ObjectId', ref: 'Warehouse' },
      { name: 'saleDate', type: 'Date', default: 'Date.now' },
      { name: 'items', type: 'ItemsArray', priceField: 'unitPrice' },
      { name: 'totalAmount', type: 'Number', default: 0 },
      { name: 'discount', type: 'Number', default: 0 },
      { name: 'paidAmount', type: 'Number', default: 0 },
      { name: 'dueAmount', type: 'Number', default: 0 },
      { name: 'paymentMethod', type: 'ObjectId', ref: 'PaymentMethod' },
      {
        name: 'status',
        type: 'String',
        enum: ['Completed', 'Due', 'Cancelled'],
        default: 'Completed',
      },
    ],
  },
  {
    key: 'damages',
    model: 'Damage',
    label: 'Damage',
    labelPlural: 'Damages',
    fields: [
      { name: 'product', type: 'ObjectId', ref: 'Product', required: true },
      { name: 'warehouse', type: 'ObjectId', ref: 'Warehouse' },
      { name: 'quantity', type: 'Number', required: true, default: 0 },
      { name: 'reason', type: 'String' },
      { name: 'date', type: 'Date', default: 'Date.now' },
      { name: 'lossAmount', type: 'Number', default: 0 },
    ],
  },
  {
    key: 'stock-transfers',
    model: 'StockTransfer',
    label: 'Stock Transfer',
    labelPlural: 'Stock Transfers',
    fields: [
      { name: 'transferNumber', type: 'String', required: true, unique: true },
      {
        name: 'fromWarehouse',
        type: 'ObjectId',
        ref: 'Warehouse',
        required: true,
      },
      {
        name: 'toWarehouse',
        type: 'ObjectId',
        ref: 'Warehouse',
        required: true,
      },
      { name: 'product', type: 'ObjectId', ref: 'Product', required: true },
      { name: 'quantity', type: 'Number', required: true, default: 0 },
      { name: 'date', type: 'Date', default: 'Date.now' },
      { name: 'note', type: 'String' },
      {
        name: 'status',
        type: 'String',
        enum: ['Pending', 'Completed'],
        default: 'Completed',
      },
    ],
  },
  {
    key: 'stock-adjustments',
    model: 'StockAdjustment',
    label: 'Stock Adjustment',
    labelPlural: 'Stock Adjustments',
    fields: [
      { name: 'product', type: 'ObjectId', ref: 'Product', required: true },
      { name: 'warehouse', type: 'ObjectId', ref: 'Warehouse' },
      {
        name: 'adjustmentType',
        type: 'String',
        enum: ['Increase', 'Decrease'],
        required: true,
      },
      { name: 'quantity', type: 'Number', required: true, default: 0 },
      { name: 'reason', type: 'String' },
      { name: 'date', type: 'Date', default: 'Date.now' },
    ],
  },
];
